# Generated by Django 5.2.1 on 2025-05-31 21:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='media/images/default_profile_avbbjz', max_length=255, null=True, verbose_name='image'),
        ),
    ]
