# Generated by Django 5.2 on 2025-05-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
